### ISSUE TITLE
Dropdown : status "disabled"

### ISSUE THREAD

**Issue by vdelacerda** [vincjo/gros#2]
Bonjour,

Est ce qu'il est possible de mettre un statut "disabled" sur le trigger du dropdown ?
Dans mon cas, il s'agirait de ne rendre accessible le dropdown que sous certaines conditions.

**Comment by vincjo** [comment]
Bonjour,

Cela vient d'être publié en `0.19.8`
Le Dropdown a une propriété `disabled: boolean`
 
Ci-dessous un exemple d'utilisation:
````svelte
<script>
    import { Dropdown } from 'gros/dropdown'
</script>

<Dropdown disabled>
    <button>Drop me!</button>
    <ul slot="content">
        <li>Option 1</li>
        <li>Option 2</li>
        <li>Option 3</li>
        <li>Option 4</li>
    </ul>
</Dropdown>
````

**Comment by vdelacerda** [comment]
Impeccable ! Merci
