### ISSUE TITLE
Dropdown - Trigger soumettant le formulaire

### ISSUE THREAD

**Issue by vdelacerda** [vincjo/gros#3]
Bonjour,

Est-ce qu'il y a une raison et est-ce obligatoire que le bouton trigger du dropdown ne soit pas typé ?
Car en l'état, si le dropdown est dans un formulaire, l'ouverture du dropdown soumet le formulaire.
N'est-il pas possible de type le bouton en type="button" ?
Merci.

**Comment by vincjo** [comment]
Bonjour,

En effet, j'ai un peu oublié que le type par défaut est "submit" pour les boutons, ce qui entraîne nécessairement des problèmes dans les formulaires.

Je viens de corriger cette erreur dans tous les composants en définissant le type="button" comme vous le signalez.
C'est publié en `0.19.9`

Merci pour votre remarque.
